### PR TITLE
Key event test cases failed in mobile-spec

### PR DESCRIPTION
**Pull request by fujunwei**
The App plugin name is CoreAndroid in Cordova 4.0.
Remove key code from hashSet when remove event listener.
Merge PR-12 that fix minSdkVersion conflict.

### CODE REVIEW

**Comment by fujunwei** [comment]
@clelland  PTAL, thanks.

**Comment by fujunwei** [comment]
@clelland @agrieve Could you please help me review this PR? thanks.

**Comment by agrieve** [comment]
Done! Thanks!

**Comment by fujunwei** [comment]
Thanks so much.

**Pull request closed without merging**
